import EmptyState from '../common/EmptyState'

function Award({ label, award, detail }) {
  if (!award) return <div className="rounded-lg border border-dashed border-slate-700 p-3"><p className="text-sm font-semibold text-slate-300">{label}</p><p className="mt-1 text-sm text-slate-500">Pending</p></div>
  return <div className="rounded-lg border border-amber-400/20 bg-amber-400/5 p-3"><p className="text-xs font-bold uppercase tracking-wide text-amber-300">{label}</p><p className="mt-1 font-semibold text-slate-100">{award.player || award.team}</p><p className="mt-1 text-sm text-slate-400">{detail(award)}</p></div>
}

export default function TournamentAwards({ awards, teamAwards }) {
  if (!awards && !teamAwards) return <EmptyState title="Awards unavailable" description="Awards will appear when the backend has sufficient completed tournament data." />
  const teams = teamAwards || {}
  return <div className="space-y-6"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Award label="Golden Boot" award={awards?.goldenBoot} detail={(award) => `${award.team} · ${award.goals} goals`} /><Award label="Golden Ball" award={awards?.goldenBall} detail={(award) => `${award.team} · ${award.averageRating?.toFixed(2)} average rating`} /><Award label="Golden Glove" award={awards?.goldenGlove} detail={(award) => `${award.team} · ${award.averageRating?.toFixed(2)} average rating`} /><Award label="Best Young Player" award={awards?.bestYoungPlayer} detail={(award) => `${award.team} · ${award.averageRating?.toFixed(2)} average rating`} /></div><div className="grid gap-3 md:grid-cols-3"><Award label="Best Attack" award={teams.bestAttack} detail={(award) => `${award.value} goals`} /><Award label="Best Defence" award={teams.bestDefence} detail={(award) => `${award.value} goals conceded`} /><Award label="Fair Play" award={teams.fairPlay} detail={(award) => `${award.value} discipline points`} /></div>{awards?.teamOfTheTournament?.length ? <div><h3 className="mb-3 text-base font-bold text-slate-100">Team of the Tournament</h3><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{awards.teamOfTheTournament.map((player) => <div key={`${player.playerId}-${player.slot}`} className="rounded-lg border border-slate-800 bg-slate-950/50 p-3"><p className="text-xs font-bold uppercase tracking-wide text-emerald-400">{player.slot} · {player.position}</p><p className="mt-1 font-semibold text-slate-100">{player.player}</p><p className="mt-1 text-sm text-slate-400">{player.team} · {player.averageRating?.toFixed(2)} rating</p></div>)}</div></div> : null}</div>
}
