import { useEffect, useMemo, useState } from 'react'
import { getAchievements } from '../api/managerApi'
import AchievementCard from '../components/achievements/AchievementCard'
import AchievementSummary from '../components/achievements/AchievementSummary'
import EmptyState from '../components/common/EmptyState'
import ErrorMessage from '../components/common/ErrorMessage'
import Loading from '../components/common/Loading'

export default function Achievements() {
  const [achievements, setAchievements] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [badge, setBadge] = useState('ALL'); const [sort, setSort] = useState('recent')
  useEffect(() => { getAchievements().then(({ data }) => setAchievements(data || [])).catch((requestError) => setError(requestError.message || 'Unable to load achievements.')).finally(() => setLoading(false)) }, [])
  const badges = useMemo(() => [...new Set(achievements.map((item) => item.badge).filter(Boolean))], [achievements])
  const visible = useMemo(() => [...achievements.filter((item) => badge === 'ALL' || item.badge === badge)].sort((first, second) => sort === 'title' ? (first.title || '').localeCompare(second.title || '') : new Date(second.unlockedAt || 0) - new Date(first.unlockedAt || 0)), [achievements, badge, sort])
  if (loading) return <Loading label="Loading achievements..." />
  return <div className="space-y-7"><div><p className="text-sm font-semibold uppercase tracking-[0.18em] text-emerald-400">Career recognition</p><h1 className="mt-2 text-3xl font-bold text-white">Achievements</h1><p className="mt-2 text-slate-400">Unlocked manager achievements and badge tiers recorded by the backend.</p></div><ErrorMessage message={error} /><AchievementSummary achievements={achievements} />{achievements.length ? <><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div className="flex flex-wrap gap-2" aria-label="Achievement badge filter"><button type="button" onClick={() => setBadge('ALL')} className={`rounded-lg px-3 py-2 text-sm font-semibold ${badge === 'ALL' ? 'bg-emerald-500 text-slate-950' : 'bg-slate-800 text-slate-300 hover:bg-slate-700'}`}>All badges</button>{badges.map((item) => <button type="button" key={item} onClick={() => setBadge(item)} className={`rounded-lg px-3 py-2 text-sm font-semibold ${badge === item ? 'bg-emerald-500 text-slate-950' : 'bg-slate-800 text-slate-300 hover:bg-slate-700'}`}>{item.replaceAll('_', ' ')}</button>)}</div><label className="text-sm font-medium text-slate-300">Sort<select value={sort} onChange={(event) => setSort(event.target.value)} className="ml-2 rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-white"><option value="recent">Recently unlocked</option><option value="title">Title</option></select></label></div>{visible.length ? <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{visible.map((achievement) => <AchievementCard key={`${achievement.code}-${achievement.unlockedAt}`} achievement={achievement} />)}</div> : <EmptyState title="No achievements in this badge tier." description="Choose another badge filter to view your unlocked achievements." />}</> : <EmptyState title="No achievements unlocked yet." description="Your unlocked manager achievements will appear here when the backend records them." />}</div>
}
