import { useCallback, useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { getAchievements, getCareerAnalytics, getCareerHistory, getCareerStatistics, getCareerTimeline, getCurrentManager } from '../api/managerApi'
import Card from '../components/common/Card'
import EmptyState from '../components/common/EmptyState'
import ErrorMessage from '../components/common/ErrorMessage'
import Loading from '../components/common/Loading'
import CareerOverview from '../components/profile/CareerOverview'
import CareerTimeline from '../components/profile/CareerTimeline'
import ProfileHeader from '../components/profile/ProfileHeader'
import { useAuth } from '../context/AuthContext'

const date = (value) => value ? new Intl.DateTimeFormat(undefined, { dateStyle: 'medium' }).format(new Date(value)) : '—'
const label = (value) => value ? value.replaceAll('_', ' ').toLowerCase().replace(/\b\w/g, (character) => character.toUpperCase()) : '—'

function Achievements({ items, loading, error }) { if (loading) return <Loading label="Loading achievements..." />; if (error) return <ErrorMessage message={error} />; return <Card><h2 className="text-xl font-bold text-white">Achievements</h2><p className="mt-1 text-sm text-slate-400">Badges unlocked in your manager career.</p>{items?.length ? <ul className="mt-5 space-y-3">{items.map((item) => <li key={`${item.code}-${item.unlockedAt}`} className="rounded-lg border border-slate-800 bg-slate-950/50 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-semibold text-white">{item.title}</h3>{item.description && <p className="mt-1 text-sm text-slate-400">{item.description}</p>}</div>{item.badge && <span className="rounded-full bg-amber-400/10 px-2 py-1 text-xs font-bold text-amber-300">{label(item.badge)}</span>}</div><p className="mt-2 text-xs text-slate-500">Unlocked {date(item.unlockedAt)}</p></li>)}</ul> : <div className="mt-5"><EmptyState title="No achievements unlocked yet." description="Complete career milestones to unlock manager badges." /></div>}</Card> }
function Analytics({ data, loading, error }) { if (loading) return <Loading label="Loading career analytics..." />; if (error) return <ErrorMessage message={error} />; if (!data) return <EmptyState title="Analytics unavailable" description="The backend has not returned manager analytics yet." />; const fields = [['Average goals scored', data.averageGoalsScored], ['Average goals conceded', data.averageGoalsConceded], ['Average possession', data.averagePossession == null ? null : `${Number(data.averagePossession).toFixed(1)}%`], ['Longest unbeaten run', data.longestUnbeatenStreak], ['Favourite formation', data.favoriteFormation], ['Favourite tactics', data.favoriteTactics], ['Most used lineup', data.mostUsedLineup], ['Most selected captain', data.mostSelectedCaptain], ['Trusted players', data.mostTrustedPlayers]].filter(([, value]) => value != null && value !== ''); return <Card><h2 className="text-xl font-bold text-white">Career analytics</h2><div className="mt-5 grid gap-3 sm:grid-cols-2">{fields.map(([title, value]) => <div key={title} className="rounded-lg border border-slate-800 bg-slate-950/50 p-3"><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">{title}</p><p className="mt-1 font-semibold text-slate-100">{typeof value === 'number' ? value.toFixed(2) : value}</p></div>)}</div></Card> }
function History({ entries, loading, error }) { if (loading) return <Loading label="Loading career history..." />; if (error) return <ErrorMessage message={error} />; return <Card><h2 className="text-xl font-bold text-white">Recent career history</h2>{entries?.length ? <div className="mt-5 space-y-3">{entries.map((entry) => <article key={entry.id} className="rounded-lg border border-slate-800 bg-slate-950/50 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-semibold text-white">{entry.tournamentId != null ? <Link to={`/tournaments/${entry.tournamentId}`} className="hover:text-emerald-300">{entry.tournamentName}</Link> : entry.tournamentName}</h3>{entry.teamId != null ? <Link to={`/teams/${entry.teamId}/squad`} className="mt-1 inline-block text-sm text-emerald-300 hover:text-emerald-200">{entry.teamName}</Link> : <p className="mt-1 text-sm text-slate-400">{entry.teamName}</p>}</div><span className="text-sm text-slate-500">{date(entry.dateCompleted)}</span></div><p className="mt-3 text-sm text-slate-400">Position {entry.finishingPosition ?? '—'} · {entry.wins ?? '—'} wins · {entry.trophies ?? '—'} trophies</p></article>)}</div> : <div className="mt-5"><EmptyState title="No completed campaigns." description="Completed tournaments will appear in your career history." /></div>}</Card> }

const GITHUB_PROFILE_URL = 'https://github.com/Adityaaprakash'

function GitHubContributions() {
  return <Card className="overflow-hidden"><div className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-semibold uppercase tracking-[0.18em] text-emerald-400">Open source</p><h2 className="mt-2 text-xl font-bold text-white">GitHub Contributions</h2><p className="mt-1 max-w-xl text-sm text-slate-400">Follow ongoing work and view the live contribution history on GitHub.</p></div><a href={GITHUB_PROFILE_URL} target="_blank" rel="noreferrer" className="inline-flex shrink-0 items-center justify-center gap-2 rounded-lg border border-slate-600 px-4 py-2 text-sm font-semibold text-slate-200 transition hover:border-emerald-400 hover:text-emerald-200"><svg aria-hidden="true" viewBox="0 0 16 16" className="h-4 w-4 fill-current"><path d="M8 0a8 8 0 0 0-2.53 15.59c.4.07.55-.17.55-.38v-1.5c-2.23.49-2.7-1.08-2.7-1.08-.36-.93-.89-1.18-.89-1.18-.73-.5.06-.49.06-.49.81.06 1.23.83 1.23.83.72 1.23 1.88.88 2.34.67.07-.52.28-.88.51-1.08-1.78-.2-3.65-.89-3.65-3.96 0-.88.31-1.59.83-2.15-.08-.2-.36-1.02.08-2.12 0 0 .68-.22 2.2.82A7.65 7.65 0 0 1 8 3.87c.68 0 1.36.09 2 .26 1.52-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.52.56.83 1.27.83 2.15 0 3.08-1.88 3.75-3.67 3.95.29.25.54.73.54 1.48v2.2c0 .21.14.46.55.38A8 8 0 0 0 8 0Z" /></svg>View profile</a></div><div aria-hidden="true" className="mt-6 grid grid-cols-[repeat(13,minmax(0,1fr))] gap-1 sm:grid-cols-[repeat(26,minmax(0,1fr))]">{Array.from({ length: 182 }, (_, index) => <span key={index} className={`aspect-square rounded-sm ${index % 11 === 0 || index % 17 === 0 ? 'bg-emerald-400/70' : index % 7 === 0 ? 'bg-emerald-400/35' : 'bg-slate-800'}`} />)}</div><div className="mt-3 flex items-center justify-between text-xs text-slate-500"><span>Contribution-style activity preview</span><span>Live activity on GitHub</span></div></Card>
}

export default function Profile() {
  const { user } = useAuth(); const [state, setState] = useState({ manager: null, statistics: null, achievements: [], analytics: null, history: [], timeline: [] }); const [loading, setLoading] = useState({ manager: true, statistics: true, achievements: true, analytics: true, history: true, timeline: true }); const [errors, setErrors] = useState({})
  const load = useCallback(async () => { const requests = { manager: getCurrentManager, statistics: getCareerStatistics, achievements: getAchievements, analytics: getCareerAnalytics, history: getCareerHistory, timeline: getCareerTimeline }; const results = await Promise.allSettled(Object.values(requests).map((request) => request())); const keys = Object.keys(requests); const nextState = {}; const nextErrors = {}; results.forEach((result, index) => { const key = keys[index]; nextState[key] = result.status === 'fulfilled' ? result.value.data : (key === 'achievements' || key === 'history' || key === 'timeline' ? [] : null); if (result.status === 'rejected') nextErrors[key] = result.reason?.message || `Unable to load ${key}.` }); setState(nextState); setErrors(nextErrors); setLoading({ manager: false, statistics: false, achievements: false, analytics: false, history: false, timeline: false }) }, [])
  useEffect(() => { load() }, [load])
  if (loading.manager) return <Loading label="Loading manager profile..." />
  return <div className="space-y-7"><div><p className="text-sm font-semibold uppercase tracking-[0.18em] text-emerald-400">Manager identity</p><p className="mt-2 text-slate-400">Your backend-recorded career, progression, achievements, and milestones.</p></div>{errors.manager && <ErrorMessage message={errors.manager} />}{state.manager ? <ProfileHeader manager={state.manager} email={user?.email} /> : <EmptyState title="Manager profile unavailable" description="Your manager profile could not be loaded." />}<GitHubContributions /><section>{loading.statistics ? <Loading label="Loading career overview..." /> : errors.statistics ? <ErrorMessage message={errors.statistics} /> : <CareerOverview statistics={state.statistics} analytics={state.analytics} />}</section><div className="grid gap-6 xl:grid-cols-2"><Achievements items={state.achievements} loading={loading.achievements} error={errors.achievements} /><Analytics data={state.analytics} loading={loading.analytics} error={errors.analytics} /></div><div className="grid gap-6 xl:grid-cols-2"><CareerTimeline events={state.timeline} /><History entries={state.history} loading={loading.history} error={errors.history} /></div><p className="text-sm text-slate-400">Explore broader <Link to="/statistics" className="font-semibold text-emerald-300 hover:text-emerald-200">statistics</Link>, <Link to="/history" className="font-semibold text-emerald-300 hover:text-emerald-200">historical intelligence</Link>, or your <Link to="/saves" className="font-semibold text-emerald-300 hover:text-emerald-200">save games</Link>.</p></div>
}
