{{- if and .Values.postgres.enabled .Values.postgres.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "worldcup.fullname" . }}-postgres-pvc
  labels:
    app.kubernetes.io/name: postgres
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.postgres.persistence.storageClass }}
  storageClassName: {{ .Values.postgres.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.postgres.persistence.size | quote }}
{{- end }}
