apiVersion: v1
kind: Secret
metadata:
  name: {{ include "worldcup.fullname" . }}-secret
type: Opaque
data:
  DB_USERNAME: {{ .Values.secret.dbUsername | b64enc | quote }}
  DB_PASSWORD: {{ .Values.secret.dbPassword | b64enc | quote }}
  JWT_SECRET: {{ .Values.secret.jwtSecret | b64enc | quote }}
