CREATE TABLE player_contracts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id BIGINT NOT NULL,
    manager_id BIGINT NOT NULL,
    status VARCHAR(30) NOT NULL,
    start_season INTEGER NOT NULL,
    expiry_season INTEGER NOT NULL,
    commitment_level VARCHAR(30) NOT NULL,
    renewal_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    terminated_at TIMESTAMP,
    CONSTRAINT fk_player_contract_player FOREIGN KEY (player_id) REFERENCES players(id),
    CONSTRAINT fk_player_contract_manager FOREIGN KEY (manager_id) REFERENCES managers(id)
);

CREATE INDEX idx_player_contracts_manager ON player_contracts(manager_id);
CREATE INDEX idx_player_contracts_status ON player_contracts(status);
