CREATE TABLE scouts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    manager_id BIGINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    evaluation_skill INT NOT NULL,
    potential_evaluation_skill INT NOT NULL,
    tactical_knowledge INT NOT NULL,
    region_specialization VARCHAR(100),
    CONSTRAINT fk_scouts_manager FOREIGN KEY (manager_id) REFERENCES managers(id) ON DELETE CASCADE
);

CREATE TABLE scouting_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    manager_id BIGINT NOT NULL,
    scout_id BIGINT NOT NULL,
    player_id BIGINT NOT NULL,
    status VARCHAR(50) NOT NULL,
    progress INT NOT NULL DEFAULT 0,
    knowledge_level VARCHAR(50) NOT NULL,
    estimated_overall_min INT,
    estimated_overall_max INT,
    estimated_potential_min INT,
    estimated_potential_max INT,
    confidence INT NOT NULL DEFAULT 0,
    tactical_compatibility INT,
    recommendation VARCHAR(50),
    created_at TIMESTAMP NOT NULL,
    completed_at TIMESTAMP,
    CONSTRAINT fk_reports_manager FOREIGN KEY (manager_id) REFERENCES managers(id) ON DELETE CASCADE,
    CONSTRAINT fk_reports_scout FOREIGN KEY (scout_id) REFERENCES scouts(id) ON DELETE CASCADE,
    CONSTRAINT fk_reports_player FOREIGN KEY (player_id) REFERENCES players(id) ON DELETE CASCADE
);

CREATE INDEX idx_scouts_manager ON scouts(manager_id);
CREATE INDEX idx_reports_manager ON scouting_reports(manager_id);
CREATE INDEX idx_reports_player ON scouting_reports(player_id);
