package com.aditya.worldcup.managers.entity;

public enum TimelineEventType {
    TOURNAMENT,
    TROPHY,
    PROMOTION,
    REPUTATION_UPGRADE,
    ACHIEVEMENT,
    MILESTONE,
    HIRED,
    SACKED,
    RESIGNED,
    PLAYER_CONTRACT_CREATED,
    PLAYER_CONTRACT_RENEWED,
    PLAYER_CONTRACT_EXPIRED,
    PLAYER_CONTRACT_TERMINATED,
    PLAYER_RETIRED,
    PLAYER_REACTIVATED
}
